# Generated by Django 5.0.6 on 2025-06-12 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Proveedor')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden de Compra')),
                ('order_date', models.DateField(verbose_name='Fecha de la Orden')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Esperada')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PARTIALLY_RECEIVED', 'Recibida Parcialmente'), ('FULLY_RECEIVED', 'Recibida Completamente'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='Estado de la Orden')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing_app.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Pedida')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Precio de Costo Acordado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_app.product', verbose_name='Producto')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing_app.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra',
                'verbose_name_plural': 'Ítems de Orden de Compra',
            },
        ),
    ]
