# Generated by Django 5.0.6 on 2025-06-12 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICAL', 'Persona Jurídica')], default='NATURAL', max_length=10, verbose_name='Tipo de Cliente')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo / Razón Social')),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Cédula / RIF')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('invoice_date', models.DateField(verbose_name='Fecha de la Factura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Monto de Impuesto')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Monto de Descuento')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Monto Total')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('VOID', 'Anulada')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del Producto en la Venta')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU en la Venta')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Precio Unitario en la Venta')),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Total de Línea')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing_app.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
            },
        ),
    ]
