# Generated by Django 5.0.6 on 2025-06-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Total de Línea'),
        ),
    ]
