# Generated by Django 5.0.6 on 2025-06-12 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU (Código Interno)')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('unit_of_measure', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de Medida')),
                ('cost_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Precio de Costo')),
                ('sale_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Precio de Venta')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nivel Mínimo de Stock')),
                ('tracking_type', models.CharField(choices=[('NONE', 'Sin Seguimiento'), ('LOT', 'Por Lote'), ('SERIAL', 'Por Número de Serie')], default='NONE', max_length=10, verbose_name='Tipo de Seguimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Almacén')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('status', models.CharField(choices=[('IN_STOCK', 'En Almacén'), ('SOLD', 'Vendido'), ('DEFECTIVE', 'Defectuoso')], default='IN_STOCK', max_length=20, verbose_name='Estado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory_app.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.warehouse', verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Número de Serie',
                'verbose_name_plural': 'Números de Serie',
            },
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en este Lote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory_app.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.warehouse', verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'unique_together': {('product', 'lot_number', 'warehouse')},
            },
        ),
    ]
