# Generated by Django 5.0.6 on 2026-01-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_stockarrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockarrival',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Costo Unitario de Entrada'),
        ),
    ]
