# Generated by Django 5.0.6 on 2026-01-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_stockarrival_unit_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productlot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Variación de Producto', 'verbose_name_plural': 'Variaciones'},
        ),
        migrations.AlterModelOptions(
            name='serialnumber',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='daily_usage_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consumo promedio diario para calcular días restantes.', max_digits=10, verbose_name='Tasa de Consumo Diario'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='Es Insumo Crítico'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Destino / Área'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad Despachada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Costo Promedio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ficha Técnica / Detalles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo en Catálogo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Mínimo (Alerta)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Descripción del Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Valor Referencia (Activo)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productlot',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlot',
            name='lot_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productlot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory_app.product'),
        ),
        migrations.AlterField(
            model_name='productlot',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productlot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.warehouse'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Tipo / Variante'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='inventory_app.product'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Medida / Especificación'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sku_variant',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU Variante'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Físico'),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory_app.product'),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='status',
            field=models.CharField(default='IN_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='stockarrival',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Costo Unitario'),
        ),
    ]
