# Generated by Django 5.0.6 on 2025-06-12 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing_app', '0001_initial'),
        ('inventory_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Nota de Entrega')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Despacho')),
                ('delivery_address', models.TextField(verbose_name='Dirección de Entrega')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'En Preparación'), ('DISPATCHED', 'Despachada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado del Despacho')),
                ('received_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recibido por (Nombre y C.I.)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing_app.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_notes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_notes', to=settings.AUTH_USER_MODEL, verbose_name='Transportista/Despachado por')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.invoice', verbose_name='Factura Asociada (Opcional)')),
            ],
            options={
                'verbose_name': 'Nota de Entrega',
                'verbose_name_plural': 'Notas de Entrega',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad a Despachar')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_app.deliverynote', verbose_name='Nota de Entrega')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_app.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Nota de Entrega',
                'verbose_name_plural': 'Ítems de Nota de Entrega',
            },
        ),
    ]
